//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPMEntities : DbContext
    {
        public EPMEntities()
            : base("name=EPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<ConsumoAgua> ConsumoAgua { get; set; }
        public virtual DbSet<ConsumoEnergia> ConsumoEnergia { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Tarifa> Tarifa { get; set; }
    }
}
